// Mapeo de componentes a sus rutas
export const componentPaths = {
  // Atoms
  "Button": "@/components/atoms/buttons/Button",
  "Input": "@/components/atoms/forms/Input",
  "Checkbox": "@/components/atoms/forms/Checkbox",
  "RadioGroup": "@/components/atoms/forms/RadioGroup",
  "Avatar": "@/components/atoms/displays/Avatar",
  "Badge": "@/components/atoms/displays/Badge",
  "Alert": "@/components/atoms/feedback/Alert",
  "Dialog": "@/components/atoms/overlay/Dialog",
  "DropdownMenu": "@/components/atoms/navigation/DropdownMenu",
  
  // Molecules
  "EventCard": "@/components/molecules/event-card",
  "OrganizerCard": "@/components/molecules/organizer-card",
  "OrganizerEventCard": "@/components/molecules/organizer-event-card",
  "MobileOrganizerSection": "@/components/molecules/mobile-organizer-section",
  
  // Organisms
  "Navbar": "@/components/organisms/navbar",
  "Footer": "@/components/organisms/footer",
  "EventsSection": "@/components/organisms/events/EventsSection",
  "EventDetailContent": "@/components/organisms/event/EventDetailContent",
  "OrganizerSection": "@/components/organisms/event/OrganizerSection",
  "EventList": "@/components/organisms/event/EventList",
  "CreatorBanner": "@/components/organisms/creator/CreatorBanner",
  
  // Home Organisms
  "HeroSection": "@/components/organisms/home/HeroSection",
  "BenefitsSection": "@/components/organisms/home/BenefitsSection",
  "HowItWorksSection": "@/components/organisms/home/HowItWorksSection",
  "TestimonialsSection": "@/components/organisms/home/TestimonialsSection",
  "FAQSection": "@/components/organisms/home/FAQSection",
  "PricingSection": "@/components/organisms/home/PricingSection",
  "FinalCTASection": "@/components/organisms/home/FinalCTASection",
  "ComparisonSection": "@/components/organisms/home/ComparisonSection",
  
  // UI Components (shadcn/ui)
  "Card": "@/components/ui/card",
  "Tabs": "@/components/ui/tabs",
  "Table": "@/components/ui/table",
  "Form": "@/components/ui/form",
  "Select": "@/components/ui/select",
  "Textarea": "@/components/ui/textarea",
  "Label": "@/components/ui/label",
  "Switch": "@/components/ui/switch",
  "Tooltip": "@/components/ui/tooltip",
  "Toast": "@/components/ui/toast",
  "Toaster": "@/components/ui/toaster",
  "Skeleton": "@/components/ui/skeleton",
  "Separator": "@/components/ui/separator",
  "Progress": "@/components/ui/progress",
  "Popover": "@/components/ui/popover",
  "NavigationMenu": "@/components/ui/navigation-menu",
  "Menubar": "@/components/ui/menubar",
  "InputOTP": "@/components/ui/input-otp",
  "HoverCard": "@/components/ui/hover-card",
  "Drawer": "@/components/ui/drawer",
  "ContextMenu": "@/components/ui/context-menu",
  "Command": "@/components/ui/command",
  "Collapsible": "@/components/ui/collapsible",
  "Calendar": "@/components/ui/calendar",
  "Breadcrumb": "@/components/ui/breadcrumb",
  "AspectRatio": "@/components/ui/aspect-ratio",
  "AlertDialog": "@/components/ui/alert-dialog",
  "Accordion": "@/components/ui/accordion",
} as const;
